baseURL = "/"
languageCode = "zh-CN"
title = "一个小地方"
theme = "maupassant"
# 默认是70
summaryLength = 40

[author]
  name = "ARLOOR"

[params.utteranc]
    enable = true
    repo = "arloor/blog"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[params]
  author = "ARLOOR"
  subtitle = "小白成长记"
  keywords = "golang,go语言,go语言笔记,飞雪无情,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4